---
title: "Untitled"
output: html_document
date: "2024-11-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(lubridate)
```

```{r}
kleaf_efm_1 <- read.csv(here("data", "raw_data", "hydraulics", "left_computer", "condcalc", "2024-11-16 quag_kleaf condcalc kleaf.csv"))
kleaf_efm_2 <- read.csv(here("data", "raw_data", "hydraulics", "right_computer", "condcalc", "2024-11-16 quag_kleaf condcalc kleaf.csv"))
leaf_area <- read.csv(here("data", "raw_data", "hydraulic_scans", "leaf_area.csv")) %>% 
  filter(Slice != "73_vpmonly_003.jpg") %>% 
  mutate(Slice = case_when(Slice == "78_forgotleaf_003.jpg" ~ "78_003.jpg",
                           T ~ Slice),
         leaf_area = Total.Area/10000) %>% 
  mutate(Slice = str_remove(Slice, ".jpg")) %>% 
  separate(Slice, into = c("tree", "branch"), sep = "_") %>% 
  select(tree, branch, leaf_area) %>% 
  group_by(tree, branch) %>% 
  reframe(leaf_area = sum(leaf_area)) %>% 
  mutate(tree = as.numeric(tree),
         branch = as.numeric(branch))

kleaf_efm <- rbind(kleaf_efm_1, kleaf_efm_2) %>% 
  distinct() %>% 
  filter(t.day > 300) %>% 
  mutate(species = "quag") %>% 
  separate(col = numbr, into = c("tree", "branch"), sep = "_") %>% 
  rename(kleaf = k.g.s.MPa) %>% 
  select(species, tree, branch, kleaf)%>% 
  mutate(tree = as.numeric(tree),
         branch = as.numeric(branch),
         treatment = case_when(tree < 90 ~ "burned",
                               tree >- 90 ~ "unburned")) %>% 
  inner_join(leaf_area, by = c("tree", "branch")) %>% 
  mutate(kleaf = kleaf/leaf_area) %>% 
  select(species, treatment, tree, branch, kleaf)
  
write.csv(kleaf_efm, here("data", "clean_data", "kleaf_efm_clean.csv"), row.names = F)
```
